version: '3'
services:

  front:
    build: front/
    ports:
      - "8080:80"
    restart: on-failure

  back:
    build: api/
    ports:
      - "4000:4000"
    networks:
      - database
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=hostname
    depends_on:
         # The DB container needs to be started before we start this container.
         - db
  db:
      # We use the predefined Postgres image.
      image: postgres:latest
      environment:
         # Set user for Postgres.
        - POSTGRES_PASSWORD=postgres
        - PGDATA=/var/lib/postgresql/data/db-files/
      restart: always
      ports:
         - 5432:5432
      networks: 
         - database
    

networks:
  database: